name: Staging Deploy

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t evuemev4-frontend:staging .

      - name: Deploy to Development
        run: |
          docker tag evuemev4-frontend:staging ${{ secrets.DOCKER_REGISTRY }}/evuemev4-frontend:staging
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_REGISTRY }}/evuemev4-frontend:staging

      - name: Deploy to Kubernetes
        run: |
          echo "${{ secrets.E2E_KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=kubeconfig
          kubectl delete -f ev-web-deployment-staging.yml --ignore-not-found=true
          kubectl apply -f ev-web-deployment-staging.yml
